//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int id { get; set; }
        public string lastname { get; set; }
        public string firstname { get; set; }
        public Nullable<int> age { get; set; }
        public int addressId { get; set; }
    
        public virtual Address Address { get; set; }

        public Employee(string lastname, string firstname, int? age, Address address)
        {
            this.lastname = lastname;
            this.firstname = firstname;
            this.age = age;
            Address = address;
        }
    }
}
